# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x07videoai\"q\n\x0b\x43hatRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\x12\x12\n\nvideo_path\x18\x02 \x01(\t\x12!\n\x19is_clarification_response\x18\x03 \x01(\x08\x12\x17\n\x0fselected_option\x18\x04 \x01(\t\"\xd4\x01\n\x0c\x43hatResponse\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".videoai.ChatResponse.ResponseType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1d\n\x15\x63larification_options\x18\x03 \x03(\t\x12\x10\n\x08\x66ile_url\x18\x04 \x01(\t\"P\n\x0cResponseType\x12\x0e\n\nTEXT_CHUNK\x10\x00\x12\x1a\n\x16\x43LARIFICATION_REQUIRED\x10\x01\x12\x14\n\x10REPORT_GENERATED\x10\x02\x32M\n\x0eVideoAIService\x12;\n\nChatStream\x12\x14.videoai.ChatRequest\x1a\x15.videoai.ChatResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=25
  _globals['_CHATREQUEST']._serialized_end=138
  _globals['_CHATRESPONSE']._serialized_start=141
  _globals['_CHATRESPONSE']._serialized_end=353
  _globals['_CHATRESPONSE_RESPONSETYPE']._serialized_start=273
  _globals['_CHATRESPONSE_RESPONSETYPE']._serialized_end=353
  _globals['_VIDEOAISERVICE']._serialized_start=355
  _globals['_VIDEOAISERVICE']._serialized_end=432
# @@protoc_insertion_point(module_scope)
